name-template: Release v$NEXT_MINOR_VERSION 🌈
tag-template: v$NEXT_MINOR_VERSION
categories:
  - title: 🚀 Features
    label:
      - feature
      - feat
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
  - title: Dependencies and Libraries
    label: 
      - dependencies
      - chore(deps)
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
template: |-
  ## Changes

  $CHANGES

  ## Contributors

  Thanks a lot to our contributors for making this release possible:
  $CONTRIBUTORS
