name: "Android Workflow"

inputs:
  STORE_PASS:
    description: 'Store Password'
    required: false
    default: ''
  ALIAS:
    description: 'Certificate Alias'
    required: false
    default: ''
  KEY_PASS:
    description: 'Key Password'
    required: false
    default: ''
  VERSION_NAME:
    description: 'Version Name to be used for build'
    required: false
    default: '1.0.0'
  VERSION_CODE:
    description: 'Version Code to be used for build'
    required: true
    default: '1'

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true

    - name: Run tests
      shell: bash
      run: flutter test
      
    - name: Build Android APK/AAB
      shell: bash
      env:
        STORE_PASS: ${{ inputs.STORE_PASS }}
        ALIAS: ${{ inputs.ALIAS }}
        KEY_PASS: ${{ inputs.KEY_PASS }}
        VERSION_NAME: ${{inputs.VERSION_NAME}}
        VERSION_CODE: ${{inputs.VERSION_CODE}}
      run: |
        flutter build apk --build-name $VERSION_NAME --build-number $VERSION_CODE
        flutter build appbundle --build-name $VERSION_NAME --build-number $VERSION_CODE