default_platform(:android)
platform :android do
    lane :buildAAB do
        gradle(task: "bundle",build_type: "Release")
    end
    lane :uploadToPlaystore do
        upload_to_play_store(track: "beta",aab:"apk/badge-magic-development-release.aab")
    end
end
